spring:
  application:
    name: auth
server.port: 9999
logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    level: '%clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %5p'
management:
  context-path: /system
security:
  ignored: /webjars/**,/js/**,/css/**,/images/**
  user:
    password: password
