spring:
  application:
    name: auth
  resources:
    chain:
      enabled: true

server:
  port: 9999
  context-path: /uaa

security:
  user:
    password: password
  ignored: 
    - /webjars/**
    - /js/**
    - /css/**
    - /images/**
    - /**/favicon.ico

logging:
  level:
    org.springframework.security: DEBUG

management:
  context-path: /system
  security:
    enabled: false
