spring:
  application:
    name: ui
  aop:
    proxy-target-class: true
  resources:
    chain:
      enabled: true

server:
  port: 8080
  session:
    cookie:
      name: UI_SESSION

security:
  ignored:
    - /webjars/**
    - /js/**
    - /css/**
    - /images/**
    - /**/favicon.ico
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://oauth.localtest.me:9999/uaa/oauth/token
      userAuthorizationUri: http://oauth.localtest.me:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
      use-current-uri: true
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

management:
  context-path: /system
  security:
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG

proxy:
  auth:
    routes:
      resouce: oauth2
      user: oauth2

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://resource.localtest.me:9000/resource
    user:
      path: /user/**
      url: http://oauth.localtest.me:9999/uaa/user
